### ISSUE TITLE
"Restart Game Key" and yes_or_no function do not respect keyboard variations

### ISSUE THREAD

**Issue by puellanivis** [usrshare/szsol#6]
Imagine my surprise when I hit "y" to select a field, then "y" again to move up that field, and my game restarted…

Neither of those were actually supposed to be a "y". I was pressing "z" both times, "z" having been remapped.

I put in AZERTY into the keyboard localization, because I knew there were a different latin layout. :P 

And then you go and break it :P

**Comment by usrshare** [comment]
Oh, sorry. Fixed. Now 1) the Z key only restarts the game on a QWERTY layout, 2) F3 can restart the game on all layouts, 3) F2 now can also start a new game without terminating the app.
